### ISSUE TITLE
Memory Allocation Issues

### ISSUE THREAD

**Issue by sumnerk** [rdagger/micropython-ili9341#14]
Can i suggest a mod to the clear method of the driver to allow the number of rows that are cleared at a time to be controlled.
Currently depending on the orientation of the screen the number of bytes allocated is either 3840 (w=240, 0 or 180 degrees) or 5120 (w=320, 90 or 270 degrees). This can cause memory allocation issues

Perhaps enabling blanking of 4 or 2 rows at a time would alleviate memory issues eg

    def clear(self, color=0, n=2):
        """Clear display.

        Args:
            color (Optional int): RGB565 color value (Default: 0 = Black).
        """
        w = self.width
        h = self.height
        # Clear display in 1024 byte blocks ?
        # not sure this is true - if w = 240 (the default orientation of 0 or 180 degrees)
        # then it's 3840 bytes and if w = 320 (if rotation is 90 or 270) it's 5120
        # so add a parameter to enable it to be done in smaller chunks due to memory
        # allocation issues. with n = 4 it seems faster than when n = 8 which is what the
        # original code had set. other n values that could be used 1,2,4,5,8,10,16,20,40,80
        # but probably best to stick to low single digits
#        if color:
#            line = color.to_bytes(2, 'big') * (w * 8)
#        else:
#            line = bytearray(w * 16)
#        for y in range(0, h, 8):
#           self.block(0, y, w - 1, y + 7, line)
        if color:
            line = color.to_bytes(2, 'big') * (w * n)
        else:
            line = bytearray(2 * w * n)
        for y in range(0, h, n):
            self.block(0, y, w - 1, y + n - 1, line)

**Comment by rdagger** [comment]
The comment regarding 1024 bytes is incorrect. The code was copied from one of my previous displays that had a resolution of 128x128 pixels. Thanks for bringing this to my attention! I have implemented your suggestion and added a demo that tests the speed of different chunk sizes. Based on my tests, larger chunk sizes always result in faster clearing speeds.
