### ISSUE TITLE
How to support png image display？

### ISSUE THREAD

**Issue by ruihua-code** [rdagger/micropython-ili9341#16]
ili9341.py in micropython, how to support png image display, thank you

**Comment by rdagger** [comment]
You can use the included utility to convert pngs to the required rgb565 format:
[img2rgb565.py](https://github.com/rdagger/micropython-ili9341/blob/master/utils/img2rgb565.py)

**Comment by ruihua-code** [comment]
> You can use the included utility to convert pngs to the required rgb565 format: [img2rgb565.py](https://github.com/rdagger/micropython-ili9341/blob/master/utils/img2rgb565.py)

Thank you for your reply. I have already done so
