### ISSUE TITLE
mirror touch axes

### ISSUE THREAD

**Issue by Synec5** [rdagger/micropython-ili9341#18]
Hello,
I can mirror touch axes in the file xpt2046.py

With kind regards

**Comment by rdagger** [comment]
If I understand correctly, you're asking about mirroring touch coordinates. If that's the case, one possible solution could be subtracting the X coordinate from the width and the Y coordinate from the height.

**Comment by rdagger** [comment]
xpt2046.py has both self.width and self.height so you just need to make the adjustment prior to the x,y values being returned in get_touch() and/or int_press().
