### ISSUE TITLE
Image formats

### ISSUE THREAD

**Issue by aleggon** [rdagger/micropython-ili9341#2]
Not exactly an issue, more a question. What image formats does the draw_image method support? I checked the images folder and found only raw files, but I could not open them as raw on my PC. Windows did not recognize them as raw.

**Comment by rdagger** [comment]
It uses raw bitmap format.  You can open, edit and save raw bitmaps using Gimp.  You would need to manually specify the format as raw image data using RGB565 big endian with the correct dimensions in pixels for width and height.
My repo includes a utility called img2rgb565.py which converts common image formats such as jpeg and png to the required raw format.
