### ISSUE TITLE
xglcd_font Extension?

### ISSUE THREAD

**Issue by urogers** [rdagger/micropython-ili9341#25]
First, much respect for your efforts on this repository.  

We use the ili9341 code set on the STM32F429 Discovery board as part of a course at our university.  The board has a large flash (2M), but because of STM32 paging issues, the user MicroPython flash is relatively small (~160k).  Thus, we freeze all the utility modules as bytecode into the firmware, which includes fonts, to free up program store for the students and their projects.

What follows is how we decided to implement that relative to your _xglcd_font.py_ file.  The question for you:  Would you like us to do a Pull request to include this as something your other users might want, or would you like us to break into a separate branch?  We are also open to counter proposals.

Rough code snippets to show the implementation:  _xglcd_font.py_

```class XglcdFont(object):
    def __init__(self, path, width, height, start_letter=32, letter_count=96, load_frozen=False):
       ...
        if load_frozen:
            self.letters = bytearray(self.bytes_per_letter * self.letter_count) # allocate space for subclass to fill.
        else:
            self.__load_xglcd_font(path)
```

Next, the font _Bally7x9_froze.py_   (This is a .py variant of your .c font file.  The .py allows it to easily be frozen as bytecode in MicroPython)

```from xglcd_font_froze import XglcdFont
from xglcd_font_froze import XglcdFont

class Bally7x9 (XglcdFont):
    def __init__(self):
        super().__init__('', 7, 9, 32, 96, True) # 7x9 font, "standard" range of letters, frozen font loaded
        font_data = [
            0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  # Code for char
            ...
            0x02, 0x7C, 0x00, 0x7C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00   # Code for char 
        ]
        self.letters = bytearray(font_data)
```

The user can use both options as they desire.  Traditional .c font files or .py font files (either frozen, or unfrozen in firmware).
```
from xglcd_font_froze import XglcdFont
from Bally7x9_froze import Bally7x9

arcadepix = XglcdFont('fonts/ArcadePix9x11.c', 9, 11)
bally = Bally7x9()
```

**Comment by rdagger** [comment]
Thanks for your proposal and the effort you've put into enhancing the functionality of xglcd_font.py! Your work could significantly benefit users, especially those facing memory constraints.

I believe that maintaining these changes in a separate branch would be the most appropriate.  Given my current time constraints, having a dedicated branch for this specific implementation will help ensure that the core project remains easily maintainable while still offering this advanced option for users who need it.

I’d be happy to add a link to your project from my repo and my website.
