### ISSUE TITLE
FrameBuffer

### ISSUE THREAD

**Issue by TamTamPy** [rdagger/micropython-ili9341#26]
Hey,

i know this is quite old code. But i was wondering... could I use the framebuf library with this?
Specifically: I want to have a "start-up-animation" like every gaming console has. But for the framebuffer to use,  i would need bitmap images.
Your library needs the raw rgb565... so I don't know where to go from here.

Maybe a little help for some micro-controlling-newbie?

TamTam

**Comment by rdagger** [comment]
The MicroPython framebuf library supports RGB565:
https://docs.micropython.org/en/latest/library/framebuf.html#framebuf.framebuf.RGB565

You could use a sprite sheet.  There's an example on my website:
https://www.rototron.info/projects/esp32-pwned-password-checker/#sprites

**Comment by rdagger** [comment]
I added an animation demo (demo_animated_sprite.py).

https://github.com/rdagger/micropython-ili9341/assets/106355/a5d91833-15cb-4cf5-a172-1b2302ce1ce8

**Comment by TamTamPy** [comment]
okay wow... this is exactly what I need!  :):):)
thank you so much !

**Comment by TamTamPy** [comment]
https://github.com/rdagger/micropython-ili9341/assets/152076757/fa4ae275-7df5-4059-a8be-69a825e324d0

would u have an idea why the animation is so slow on my setup?

ESP32-S3  (Arduino Nano Version)
Micropython (of course)
