### ISSUE TITLE
Touch functionality for RPi Pico

### ISSUE THREAD

**Issue by sjkahel** [rdagger/micropython-ili9341#28]
Hi, 

I was looking into using the libraries to implement in rpi pico but I have tried everything but it just did not work. 
Any ideas or any test code that you might have to implement this?

**Comment by rdagger** [comment]
Thank you for submitting this issue! It looks like this is similar to an existing issue:
https://github.com/rdagger/micropython-ili9341/issues/27

To keep our discussion centralized, I encourage you to add any additional information you have to the original issue. This helps keep all relevant information in one place and serves everyone better. I'll be marking this issue as a duplicate and closing it, but please feel free to continue the conversation on the original thread. Thanks for your understanding!
