### ISSUE TITLE
Forked and updated for s2 mini

### ISSUE THREAD

**Issue by wolfen351** [rdagger/micropython-ili9341#9]
Hi there, 

I thought I'd pop you a message and let you know that I forked your code and made a minimum version of the library code for the lolin s2 mini with the lolin tft 2.4 shield. 

Thanks for making this!

https://github.com/wolfen351/micropython-s2mini-wemos-tft-shield-ili9341-xpt2046

**Comment by rdagger** [comment]
Happy the code was helpful!
